[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "flask"
  port = 5000
