# Note: For free deployment, don't use this yaml file directly
# Instead, create the services manually as described in the README
services:
  - type: web
    name: wine-preference-app
    env: python
    plan: free # Explicitly use free tier
    buildCommand: pip install -r requirements.txt && python initialize_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///wine_database.db # Using SQLite for free tier
        # For PostgreSQL (paid tier):
        # fromDatabase:
        #   name: wine-preference-db
        #   property: connectionString

# PostgreSQL database (requires paid tier)
# databases:
#   - name: wine-preference-db
#     databaseName: wine_preferences
#     plan: free
