"""empty message

Revision ID: 42511b96b959
Revises: f394bac0d1b7
Create Date: 2025-02-28 16:21:30.306572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42511b96b959'
down_revision = 'f394bac0d1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference_backup')
    op.drop_table('wine_backup')
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variety_sub1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('variety_sub2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.drop_column('variety_sub2')
        batch_op.drop_column('variety_sub1')

    op.create_table('wine_backup',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('variety', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('acidity', mysql.FLOAT(), nullable=True),
    sa.Column('tannin', mysql.FLOAT(), nullable=True),
    sa.Column('body', mysql.FLOAT(), nullable=True),
    sa.Column('sweetness', mysql.FLOAT(), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_preference_backup',
    sa.Column('id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('wine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
