"""empty message

Revision ID: fa7f9a63803a
Revises: 42511b96b959
Create Date: 2025-02-28 16:34:08.923978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f9a63803a'
down_revision = '42511b96b959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vintage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wine_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.drop_column('wine_type')
        batch_op.drop_column('vintage')

    # ### end Alembic commands ###
